# Specify configuration 

elisa_input_files:
  - data/RBD_depletion_RLU/RBDdepletion_ELISAlayout_091121.csv

virus_titers: data/virus_titer_RLU/ACE2clones_Wu_1_RLU.csv

resultsdir: results/

summary_dir: results/summary

