# Specify configuration

elisa_input_files:
  - data/RBD_depletion_RLU/RBDdepletion_ELISAlayout_091121.csv

depletion_neuts:
   data/RBD_depletion_neuts/depletion_neuts_clone_A.csv: very_low_ACE2
   data/RBD_depletion_neuts/depletion_neuts_clone_C.csv: low_ACE2
   data/RBD_depletion_neuts/depletion_neuts_clone_G.csv: medium_ACE2
   data/RBD_depletion_neuts/depletion_neuts_consensus_kozak.csv: high_ACE2

mAb_neuts: data/mAb_neuts/mAB_neuts_frac_infectivity.csv

virus_titers: data/virus_titer_RLU/ACE2clones_Wu_1_RLU.csv

sample_information: data/serum_sample_info/sample_information.csv

resultsdir: results/

summary_dir: results/summary

neuts: results/neuts.csv

# the neutralization limit of detection is equal to the starting dilution
NT50_LOD: 25
